############################################
### BASE URL & AUTH
############################################
@baseUrl = http://127.0.0.1:8000
@empUrl = http://127.0.0.1:8000/api/employee
@hrUrl = http://127.0.0.1:8000/api/hr
@adminUrl = http://127.0.0.1:8000/api/admin
@pmUrl = http://127.0.0.1:8000/api/pm

@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyb290QGdtYWlsLmNvbSIsImV4cCI6MTc2NDk0NzkxNH0._UmgRI0vU2I4oS9JiZDuBmIF0XEJtpJ7Ot9soQhm9Oo
@pmToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwbUBnbWFpbC5jb20iLCJleHAiOjE3NjQ5NjAyOTB9.DPbhd_RpDQU6Ggw08anFYSBPtnQZ6Xe82D-tdmbIlDE
@hrToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJockBnbWFpbC5jb20iLCJleHAiOjE3NjUwNDEwNTF9.JiHkzBqIZOEsJutMT78Wc8s0ggmXivTOn5ftOuHRqqA
@empToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlbXBAZ21haWwuY29tIiwiZXhwIjoxNzY0OTYwOTU4fQ.JnvMr-NORs5Hs8KFMlnJAH2jlva-vSAxW8JYjtyFubk

############################################
### Checking
############################################

GET {{baseUrl}}

############################################
### Login
############################################

### LOGIN ENDPOINT CHECK
GET {{baseUrl}}/user/login

### LOGIN (Admin)
POST {{baseUrl}}/user/login
Content-Type: application/json

{
  "email": "root@gmail.com",
  "password": "root@gmail.com"
}

### LOGIN (Product Manager)
POST {{baseUrl}}/user/login
Content-Type: application/json

{
  "email": "pm@gmail.com",
  "password": "pm@gmail.com"
}

### LOGIN (HR)
POST {{baseUrl}}/user/login
Content-Type: application/json

{
  "email": "hr@gmail.com",
  "password": "hr@gmail.com"
}


### LOGIN (Employee)
POST {{baseUrl}}/user/login
Content-Type: application/json

{
  "email": "emp@gmail.com",
  "password": "emp@gmail.com"
}

###########################################
###TOP APIS
###########################################

#ADMIN
### Summary
GET {{adminUrl}}/summary
Authorization: Bearer {{adminToken}}

### Get Updates
GET {{adminUrl}}/updates
Authorization: Bearer {{adminToken}}

#PM
### Dashboard
GET {{pmUrl}}/dashboard
Authorization: Bearer {{pmToken}}

### Employee Performance
GET {{pmUrl}}/employee/performance/1
Authorization: Bearer {{pmToken}}

#HR
### Get all courses
GET {{hrUrl}}/course
Authorization: Bearer {{hrToken}}

### Create Policies
POST {{hrUrl}}/policies
Authorization: Bearer {{hrToken}}
Content-Type: application/json

{
  "id":"1",
  "title":"first quality check",
  "content":"anything"
}

#EMPLOYEE
### Dashboard
GET {{empUrl}}/dashboard
Authorization: Bearer {{empToken}}

### Submit leave request
POST {{empUrl}}/requests/leave
Authorization: Bearer {{empToken}}
Content-Type: application/json

{
  "leave_type": "Sick Leave",
  "from_date": "2025-01-20T00:00:00",
  "to_date": "2025-01-22T00:00:00",
  "reason": "Fever & cold"
}