import logging
from app.celery_app import celery_app
from app.database import get_session
from app.core.agents.pm_agents.pm_requirements_agent import get_pm_requirements_agent
from app.tasks.email_tasks import send_email_task

logger = logging.getLogger(__name__)


@celery_app.task(bind=True, max_retries=2)
def analyze_project_requirements_ai(
    self,
    project_id: int, 
    new_requirement_id: int = None,
    notify_email: str = None
):
    """
    Analyze project requirements using AI agent and generate execution report.
    
    Args:
        project_id: Project ID to analyze
        new_requirement_id: ID of newly added requirement
        notify_email: Email address to send report to
    """
    try:
        logger.info(f"Starting AI analysis for project {project_id}")
        
        # Get database session
        session = next(get_session())
        
        # Get AI agent
        agent = get_pm_requirements_agent(session)
        
        # Perform AI-powered analysis
        report = agent.analyze(project_id, new_requirement_id)
        
        if "error" in report:
            logger.error(f"AI Analysis failed: {report['error']}")
            # Retry with exponential backoff
            raise self.retry(exc=Exception(report['error']), countdown=60 * (2 ** self.request.retries))
        
        # Generate and send email report if email provided
        if notify_email:
            send_requirement_report_email.delay(report, notify_email)
        
        logger.info(f"AI Analysis completed successfully for project {project_id}")
        return {"status": "success", "report": report}
        
    except Exception as e:
        logger.error(f"Error in AI requirement analysis task: {str(e)}", exc_info=True)
        if self.request.retries < self.max_retries:
            raise self.retry(exc=e, countdown=60 * (2 ** self.request.retries))
        return {"status": "error", "message": str(e)}


@celery_app.task
def send_requirement_report_email(report: dict, email: str):
    """
    Send AI-generated requirement analysis report via email.
    
    Args:
        report: AI-generated analysis report dictionary
        email: Recipient email address
    """
    try:
        project_name = report.get("project", {}).get("project_name", "Unknown Project")
        
        # Generate email subject
        subject = f"🤖 AI-Powered Project Analysis: {project_name}"
        
        # Generate plain text body
        body = _generate_text_report(report)
        
        # Generate HTML body
        html_body = _generate_html_report(report)
        
        # Send email
        return send_email_task.delay(email, subject, body, html_body)
        
    except Exception as e:
        logger.error(f"Error sending AI requirement report: {str(e)}", exc_info=True)
        return {"status": "error", "message": str(e)}


def _generate_text_report(report: dict) -> str:
    """Generate plain text AI report."""
    project = report.get("project", {})
    summary = report.get("summary", {})
    recommendations = report.get("recommendations", [])
    
    text = f"""
🤖 AI-POWERED PROJECT REQUIREMENTS ANALYSIS
==========================================

Project: {project.get('project_name', 'Unknown')}
Project ID: {project.get('project_id', 'Unknown')}
Client: {project.get('client_name', 'Unknown')}
Status: {project.get('status', 'Unknown')}
Analysis Date: {report.get('analysis_date', 'Unknown')}
Generated by: {report.get('generated_by', 'AI Agent')}

SUMMARY
-------
Total Requirements: {summary.get('total_requirements', 0)}
✅ Completed: {summary.get('completed', 0)}
🔄 In Progress: {summary.get('in_progress', 0)}
⏳ Pending: {summary.get('pending', 0)}
📊 Completion Rate: {summary.get('completion_rate', 0)}%

AI ANALYSIS
-----------
{summary.get('ai_analysis', 'No analysis available')}

"""
    
    if report.get('new_requirement'):
        text += f"""
🆕 NEW REQUIREMENT ADDED
-----------------------
ID: {report['new_requirement'].get('requirement_id', 'Unknown')}
Description: {report['new_requirement'].get('description', 'No description')}

"""
    
    text += """
🎯 EXECUTION PLAN
-----------------
"""
    
    for phase in report.get('execution_plan', []):
        text += f"""
{phase.get('phase', 'Unknown Phase')} - Priority: {phase.get('priority', 'UNKNOWN')}
{phase.get('rationale', 'N/A')}
Requirements: {len(phase.get('requirements', []))}
"""
    
    if report.get('execution_plan_narrative'):
        text += f"""

AI EXECUTION INSIGHTS
--------------------
{report.get('execution_plan_narrative', '')}
"""
    
    text += """

💡 AI RECOMMENDATIONS
--------------------
"""
    for i, rec in enumerate(recommendations, 1):
        text += f"{i}. {rec}\n"
    
    text += """

---
This report was generated by an AI Agent using LangGraph and Groq AI.
The insights are based on current project data and best practices.
"""
    
    return text


def _generate_html_report(report: dict) -> str:
    """Generate beautiful HTML AI report."""
    project = report.get("project", {})
    summary = report.get("summary", {})
    recommendations = report.get("recommendations", [])
    
    # Status color mapping
    completion_rate = summary.get('completion_rate', 0)
    if completion_rate >= 70:
        status_color = "#28a745"
        status_emoji = "🟢"
    elif completion_rate >= 40:
        status_color = "#ffc107"
        status_emoji = "🟡"
    else:
        status_color = "#dc3545"
        status_emoji = "🔴"
    
    html = f"""
    <html>
        <head>
            <style>
                body {{ font-family: 'Segoe UI', Arial, sans-serif; line-height: 1.6; color: #333; background-color: #f5f5f5; }}
                .container {{ max-width: 900px; margin: 0 auto; padding: 20px; background-color: white; }}
                .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 10px; margin-bottom: 20px; }}
                .header h1 {{ margin: 0; font-size: 28px; }}
                .header .subtitle {{ opacity: 0.9; margin-top: 10px; }}
                .ai-badge {{ display: inline-block; background-color: rgba(255,255,255,0.2); padding: 5px 15px; border-radius: 20px; font-size: 12px; margin-top: 10px; }}
                .section {{ margin: 20px 0; padding: 20px; background-color: #fff; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
                .section h2 {{ color: #667eea; margin-top: 0; border-bottom: 2px solid #667eea; padding-bottom: 10px; }}
                .summary-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin: 20px 0; }}
                .stat-box {{ padding: 20px; background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%); border-radius: 8px; text-align: center; }}
                .stat-number {{ font-size: 32px; font-weight: bold; color: {status_color}; }}
                .stat-label {{ font-size: 13px; color: #666; margin-top: 5px; }}
                .ai-analysis {{ padding: 20px; background-color: #f8f9fa; border-left: 4px solid #667eea; border-radius: 4px; margin: 15px 0; white-space: pre-wrap; }}
                .phase {{ margin: 15px 0; padding: 15px; border-radius: 8px; background-color: white; border: 2px solid #e0e0e0; }}
                .phase h3 {{ margin-top: 0; color: #764ba2; }}
                .priority-high {{ border-left: 4px solid #dc3545; background-color: #fff5f5; }}
                .priority-medium {{ border-left: 4px solid #ffc107; background-color: #fffef5; }}
                .priority-low {{ border-left: 4px solid #28a745; background-color: #f5fff5; }}
                .recommendation {{ padding: 15px; margin: 10px 0; background: linear-gradient(to right, #e7f3ff, #ffffff); border-left: 4px solid #2196F3; border-radius: 4px; }}
                .new-req {{ padding: 15px; background: linear-gradient(to right, #d4edda, #ffffff); border: 2px solid #28a745; border-radius: 8px; margin: 15px 0; }}
                .footer {{ margin-top: 30px; padding: 20px; border-top: 2px solid #e0e0e0; text-align: center; color: #666; font-size: 13px; }}
                .completion-badge {{ font-size: 48px; font-weight: bold; color: {status_color}; text-align: center; margin: 20px 0; }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>🤖 AI-Powered Requirements Analysis</h1>
                    <div class="subtitle">
                        <strong>Project:</strong> {project.get('project_name', 'Unknown')}<br>
                        <strong>Client:</strong> {project.get('client_name', 'Unknown')}<br>
                        <strong>Status:</strong> {project.get('status', 'Unknown')}
                    </div>
                    <div class="ai-badge">Powered by Groq AI + LangGraph</div>
                </div>
                
                <div class="section">
                    <h2>📊 Project Overview</h2>
                    <div class="summary-grid">
                        <div class="stat-box">
                            <div class="stat-number">{summary.get('total_requirements', 0)}</div>
                            <div class="stat-label">Total Requirements</div>
                        </div>
                        <div class="stat-box">
                            <div class="stat-number" style="color: #ffc107;">⏳ {summary.get('pending', 0)}</div>
                            <div class="stat-label">Pending</div>
                        </div>
                        <div class="stat-box">
                            <div class="stat-number" style="color: #2196F3;">🔄 {summary.get('in_progress', 0)}</div>
                            <div class="stat-label">In Progress</div>
                        </div>
                        <div class="stat-box">
                            <div class="stat-number" style="color: #28a745;">✅ {summary.get('completed', 0)}</div>
                            <div class="stat-label">Completed</div>
                        </div>
                    </div>
                    <div class="completion-badge">
                        {status_emoji} {summary.get('completion_rate', 0)}%
                        <div style="font-size: 16px; color: #666; margin-top: 5px;">Completion Rate</div>
                    </div>
                </div>
    """
    
    if summary.get('ai_analysis'):
        html += f"""
                <div class="section">
                    <h2>🧠 AI Analysis</h2>
                    <div class="ai-analysis">{summary.get('ai_analysis', 'No analysis available')}</div>
                </div>
        """
    
    if report.get('new_requirement'):
        html += f"""
                <div class="new-req">
                    <h3 style="margin-top: 0; color: #28a745;">🆕 New Requirement Added</h3>
                    <p><strong>ID:</strong> {report['new_requirement'].get('requirement_id', 'Unknown')}</p>
                    <p><strong>Description:</strong> {report['new_requirement'].get('description', 'No description')}</p>
                </div>
        """
    
    html += """
                <div class="section">
                    <h2>🎯 AI-Generated Execution Plan</h2>
    """
    
    for phase in report.get('execution_plan', []):
        priority_class = f"priority-{phase.get('priority', 'medium').lower()}"
        html += f"""
                    <div class="phase {priority_class}">
                        <h3>{phase.get('phase', 'Unknown Phase')}</h3>
                        <p><strong>Priority:</strong> <span style="color: {status_color};">{phase.get('priority', 'UNKNOWN')}</span></p>
                        <p><strong>Rationale:</strong> {phase.get('rationale', 'N/A')}</p>
                        <p><strong>Requirements:</strong> {len(phase.get('requirements', []))}</p>
                    </div>
        """
    
    if report.get('execution_plan_narrative'):
        html += f"""
                    <div class="ai-analysis" style="margin-top: 20px;">
                        <h4 style="margin-top: 0;">💭 AI Execution Insights</h4>
                        {report.get('execution_plan_narrative', '')}
                    </div>
        """
    
    html += """
                </div>
                
                <div class="section">
                    <h2>💡 AI Recommendations</h2>
    """
    
    for rec in recommendations:
        html += f"""
                    <div class="recommendation">{rec}</div>
        """
    
    html += f"""
                </div>
                
                <div class="footer">
                    <p><strong>Generated by:</strong> {report.get('generated_by', 'AI Agent')}</p>
                    <p><strong>Model:</strong> {report.get('model', 'Unknown')}</p>
                    <p><strong>Analysis Date:</strong> {report.get('analysis_date', 'Unknown')}</p>
                    <p style="margin-top: 15px;">This report was generated using advanced AI techniques including LangGraph workflows and Groq AI.</p>
                    <p>The insights provided are based on current project data and industry best practices.</p>
                </div>
            </div>
        </body>
    </html>
    """
    
    return html
